# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# https://mestrak.com/blog/semantic-release-with-python-poetry-github-actions-20nn

name: CI pull request
on:
  pull_request:
    branches: [ master ]

jobs:
  TestPR:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python Poetry
      uses: abatilo/actions-poetry@v2.1.2
      with:
        poetry-version: 1.1.6
    - name: View poetry version
      run: poetry --version
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest -sv --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        env_vars: PYTHON
        name: codecov-fastai_minima
        fail_ci_if_error: true
